sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t amitvill/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true amitvill/docker-react npm run test